### ISSUE TITLE
IP-COUNTRY-REGION-CITY-ISP.BIN is locked

### ISSUE THREAD

**Issue by wc-anasser** [ip2location/ip2location-dotnet#5]
Hi, 

We are using the IP2Location Nuget Package (ver 8.6.3)
We have a service that downloads the zip file extracts it and overwrites the IP-COUNTRY-REGION-CITY-ISP.BIN file.

It seems another method in this library locks this file.

Can you please help?

Thanks.
Amir.

**Comment by ip2location-com** [comment]
If you're using ASP.NET, you can just call `iisreset` to release the lock then replace the file. Or stop the IIS, replace the file then restart the IIS.

If you have your own .NET app, you can call the IP2Location Close() function which will destroy the memory mapped file (assuming you are using that mode). Then you can replace the file before performing more queries.

**Comment by miksh7** [comment]
using UseMemoryMappedFile=true should read the bin file into memory and do all lookups in the memory.

- What is reason to keep the bin file opened (and thus locked)? 
- If you keep it open do you really keep it in memory?

**Comment by ip2location-com** [comment]
We are not reading the file into memory ourselves. The operating system is doing it automatically based on what parts of the file is needed to be read. Not all of the file is loaded into memory. The [MemoryMappedFile class ](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile?view=netframework-4.8) keeps a file handle open to load data as whenever needed. That's why we have created the IP2Location Close function to destroy the memory mapped file and close all resources.
